#!/bin/bash
# Wireproxy Installation and Setup Module
# Installs wgcf, wireproxy, and configures systemd service (does not start)

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
WGCF_VERSION="2.2.29"
WIREPROXY_VERSION="1.0.9"
WARP_DIR="/etc/wireproxy"
WARP_CONFIG="${WARP_DIR}/wireproxy.conf"
WG_PROFILE="${WARP_DIR}/wgcf-profile.conf"
WGCF_ACCOUNT="${WARP_DIR}/wgcf-account.toml"

# Default SOCKS5 bind address
SOCKS_BIND="127.0.0.1:25344"

# Detect architecture
detect_arch() {
    local arch=$(uname -m)
    case $arch in
        x86_64)
            echo "amd64"
            ;;
        aarch64|arm64)
            echo "arm64"
            ;;
        armv7l)
            echo "armv7"
            ;;
        *)
            echo -e "${RED}Unsupported architecture: $arch${NC}"
            exit 1
            ;;
    esac
}

# Install wgcf (WARP registration tool)
install_wgcf() {
    echo -e "${YELLOW}Installing wgcf...${NC}"
    
    if [ -f /usr/local/bin/wgcf ]; then
        echo -e "${GREEN}wgcf already installed${NC}"
        return 0
    fi
    
    local arch=$(detect_arch)
    local url="https://github.com/ViRb3/wgcf/releases/download/v${WGCF_VERSION}/wgcf_${WGCF_VERSION}_linux_${arch}"
    
    curl -L -o /usr/local/bin/wgcf "$url"
    chmod +x /usr/local/bin/wgcf
    
    echo -e "${GREEN}✓ wgcf installed${NC}"
}

# Install wireproxy
install_wireproxy() {
    echo -e "${YELLOW}Installing wireproxy...${NC}"
    
    if [ -f /usr/local/bin/wireproxy ]; then
        echo -e "${GREEN}wireproxy already installed${NC}"
        return 0
    fi
    
    local arch=$(detect_arch)
    local url="https://github.com/pufferffish/wireproxy/releases/download/v${WIREPROXY_VERSION}/wireproxy_linux_${arch}.tar.gz"
    
    curl -L -o /tmp/wireproxy.tar.gz "$url"
    tar -xzf /tmp/wireproxy.tar.gz -C /tmp
    mv /tmp/wireproxy /usr/local/bin/wireproxy
    chmod +x /usr/local/bin/wireproxy
    rm -f /tmp/wireproxy.tar.gz
    
    echo -e "${GREEN}✓ wireproxy installed${NC}"
}

# Register WARP account
register_warp() {
    echo -e "${YELLOW}Registering WARP account...${NC}"
    
    mkdir -p "$WARP_DIR"
    cd "$WARP_DIR"
    
    if [ -f "$WGCF_ACCOUNT" ]; then
        echo -e "${GREEN}WARP account already exists${NC}"
    else
        /usr/local/bin/wgcf register --accept-tos
        echo -e "${GREEN}✓ WARP account registered${NC}"
    fi
    
    # Generate WireGuard profile
    if [ -f "$WG_PROFILE" ]; then
        echo -e "${GREEN}WireGuard profile already exists${NC}"
    else
        /usr/local/bin/wgcf generate
        echo -e "${GREEN}✓ WireGuard profile generated${NC}"
    fi
}

# Apply WARP+ license key (optional)
apply_license() {
    local license_key=$1
    
    if [ -z "$license_key" ]; then
        echo -e "${YELLOW}No license key provided, using free WARP${NC}"
        return 0
    fi
    
    echo -e "${YELLOW}Applying WARP+ license key...${NC}"
    
    cd "$WARP_DIR"
    /usr/local/bin/wgcf update --license-key "$license_key"
    /usr/local/bin/wgcf generate
    
    echo -e "${GREEN}✓ WARP+ license applied${NC}"
}

# Generate wireproxy configuration using WGConfig reference
generate_wireproxy_config() {
    local wg_config=${1:-$WG_PROFILE}
    local socks_bind=${2:-$SOCKS_BIND}
    
    echo -e "${YELLOW}Generating wireproxy configuration...${NC}"
    
    mkdir -p "$WARP_DIR"
    
    # Create wireproxy configuration using WGConfig reference
    cat > "$WARP_CONFIG" <<EOF
# Wireproxy Configuration
# Generated by wireproxy-setup.sh
# Reference WireGuard config file directly

WGConfig = $wg_config

[Socks5]
BindAddress = $socks_bind
EOF
    
    chmod 600 "$WARP_CONFIG"
    
    echo -e "${GREEN}✓ wireproxy configuration generated: $WARP_CONFIG${NC}"
    echo -e "  WGConfig: $wg_config"
    echo -e "  SOCKS5 bind: $socks_bind"
}

# Create systemd service
create_systemd_service() {
    echo -e "${YELLOW}Creating systemd service...${NC}"
    
    cat > /etc/systemd/system/wireproxy.service <<EOF
[Unit]
Description=Wireproxy SOCKS5 Proxy
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/wireproxy -c $WARP_CONFIG
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    
    echo -e "${GREEN}✓ systemd service created (not started)${NC}"
    echo -e "${YELLOW}  To start: systemctl start wireproxy${NC}"
    echo -e "${YELLOW}  To enable: systemctl enable wireproxy${NC}"
}

# Display setup summary
display_summary() {
    echo ""
    echo -e "${GREEN}=====================================${NC}"
    echo -e "${GREEN}Wireproxy Setup Complete${NC}"
    echo -e "${GREEN}=====================================${NC}"
    echo ""
    echo "Configuration files:"
    echo "  - WARP account: $WGCF_ACCOUNT"
    echo "  - WireGuard profile: $WG_PROFILE"
    echo "  - Wireproxy config: $WARP_CONFIG"
    echo ""
    echo "Commands:"
    echo "  - Start: systemctl start wireproxy"
    echo "  - Stop: systemctl stop wireproxy"
    echo "  - Status: systemctl status wireproxy"
    echo "  - Enable: systemctl enable wireproxy"
    echo "  - Logs: journalctl -u wireproxy -f"
    echo ""
    echo "Test:"
    echo "  curl --proxy socks5h://127.0.0.1:25344 https://1.1.1.1/cdn-cgi/trace"
    echo ""
    echo -e "${YELLOW}Note: Service is NOT started. Start manually after verification.${NC}"
    echo -e "${GREEN}=====================================${NC}"
    echo ""
}

# Full setup
setup() {
    local license_key=${1:-}
    local socks_bind=${2:-$SOCKS_BIND}
    
    echo -e "${YELLOW}=====================================${NC}"
    echo -e "${YELLOW}Wireproxy Setup${NC}"
    echo -e "${YELLOW}=====================================${NC}"
    echo ""
    
    install_wgcf
    install_wireproxy
    register_warp
    
    if [ -n "$license_key" ]; then
        apply_license "$license_key"
    fi
    
    generate_wireproxy_config "$WG_PROFILE" "$socks_bind"
    create_systemd_service
    display_summary
}

# Show usage
show_usage() {
    cat <<EOF
Usage: $0 <command> [options]

Commands:
  setup [license-key] [socks-bind]   Full setup (install, register, configure)
  register                            Register WARP account only
  generate <wg-config> [socks-bind]   Generate wireproxy config from WireGuard file
  service                             Create systemd service only

Options:
  wg-config      Path to WireGuard config file (e.g., /path/to/wg.conf)
  socks-bind     SOCKS5 bind address (default: 127.0.0.1:25344)
  license-key    WARP+ license key (optional, for premium)

Examples:
  $0 setup                                       # Basic setup with free WARP
  $0 setup "xxxx-xxxx-xxxx-xxxx"                 # Setup with WARP+ license
  $0 generate /path/to/wg.conf                   # Use existing WireGuard config
  $0 generate /path/to/wg.conf 127.0.0.1:40000   # Custom SOCKS5 port
  $0 service                                     # Create systemd service only

Files:
  Config dir: $WARP_DIR
  Wireproxy config: $WARP_CONFIG

EOF
}

# CLI interface
case "${1:-}" in
    setup)
        setup "${2:-}" "${3:-$SOCKS_BIND}"
        ;;
    register)
        install_wgcf
        register_warp
        ;;
    generate)
        if [ -z "${2:-}" ]; then
            echo -e "${RED}Error: wg-config path required${NC}"
            echo "Usage: $0 generate <wg-config> [socks-bind]"
            exit 1
        fi
        generate_wireproxy_config "${2}" "${3:-$SOCKS_BIND}"
        ;;
    service)
        create_systemd_service
        ;;
    --help|-h|help|"")
        show_usage
        ;;
    *)
        echo -e "${RED}Unknown command: $1${NC}"
        show_usage
        exit 1
        ;;
esac

